version: '3.7'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bank
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - bank_network
    restart: always
    ports:
      - "5432:5432"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:root@postgres:5432/simple_bank?sslmode=disable
    networks:
      - bank_network
    depends_on:
      - postgres
    entrypoint:
      [
        "/app//wait-for.sh",
        "postgres:5432",
        "--",
        "/app/start.sh"
      ]
    command: [ "/app/main" ]

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - bank_network
    restart: always

networks:
  bank_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16

volumes:
  pg_data: