apiVersion: v1
kind: Service
metadata:
  name: simple-bank-api-service
  namespace: demo
spec:
  selector:
    app: simple-bank-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http-server
      name: http-service
  type: LoadBalancer
